version: "3.8"
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx_c
    ports:
      - "443:443"

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_c
    