version: "3.8"

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/Desktop/data/mariadb

services:
  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx_c
  #   ports:
  #     - "443:443"

  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    container_name: mariadb_c
    ports:
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql
    stdin_open: true
    tty: true

 

    