version: "3.8"
services:
  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx_c
  #   ports:
  #     - "443:443"

  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    container_name: mariadb_c
    ports:
      - "3306:3306"
    # volumes:
    #   - ./mysql:/var/lib/mysql
    stdin_open: true
    tty: true

    