version: "3.8"

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/Desktop/data/mariadb
  wordpress_v:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/Desktop/data/wordpress
    

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx_c
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html

  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    container_name: mariadb_c
    ports:
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql
    stdin_open: true
    tty: true

  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    build: ./requirements/wordpress
    container_name: wordpress_c
    # command: ["tail","-f","/dev/null"]
    ports:
      - "9000:9000"
    volumes:
      - wordpress_v:/var/www/html



 

    