version: "3.8"

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb
  wordpress_v:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress
    
networks:
  local:
    driver: bridge

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx_c
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - local
    

  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    container_name: mariadb_c
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql
    networks:
      - local
    stdin_open: true
    tty: true

  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    build: ./requirements/wordpress
    container_name: wordpress_c
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - local


 

    